apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: bulk-pack-processor
  labels:
    app: bulk-pack-processor
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        app: bulk-pack-processor
    spec:
      template:
        spec:
          containers:
            - name: bulk-pack-processor
              image: greenstand/bulk-pack-processor:latest
              imagePullPolicy: Always
              env:
              - name: DATA_INPUT_DB_URL
                valueFrom:
                  secretKeyRef:
                    name: bulk-pack-database-connection
                    key: db
              - name: DATA_INPUT_SERVICE_URL
                value: "https://dev-k8s.treetracker.org/bp-transformer/"
              - name: NODE_LOG_LEVEL
                value: trace
              - name: REMOTE_LOG_URL
                value: http://104.131.78.177:8000
          restartPolicy: Never

      