apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: bulk-pack-processor
  labels:
    app: bulk-pack-processor
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  schedule: "*/5 * * * *"
  startingDeadlineSeconds: 200
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        app: bulk-pack-processor
    spec:
      template:
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: doks.digitalocean.com/node-pool
                        operator: In
                        values:
                          - microservices-node-pool
          containers:
            - name: bulk-pack-processor
              image: greenstand/bulk-pack-processor:TAG
              imagePullPolicy: IfNotPresent
              env:
                - name: DATA_INPUT_DB_URL
                  valueFrom:
                    secretKeyRef:
                      name: bulk-pack-database-connection
                      key: db
                - name: DATA_INPUT_SERVICE_URL
                  value: "http://bulk-pack-transformer.bulk-pack-services/"
                - name: DATA_INPUT_SERVICE_URL_V2
                  value: "http://bulk-pack-transformer-v2.bulk-pack-services/"
          restartPolicy: Never
