apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: bulk-pack-processor
  labels:
    app: bulk-pack-processor
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        app: bulk-pack-processor
    spec:
      template:
        spec:
          containers:
            - name: bulk-pack-processor
              image: greenstand/bulk-pack-processor:TAG
              imagePullPolicy: IfNotPresent
              env:
              - name: DATA_INPUT_DB_URL
                valueFrom:
                  secretKeyRef:
                    name: bulk-pack-database-connection
                    key: db
              - name: DATA_INPUT_SERVICE_URL
                value: "http://bulk-pack-transformer.bulk-pack-services/"
          restartPolicy: Never
          startingDeadlineSeconds: 200

      
